version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
    - db_model:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cambiame
#      MYSQL_DATABASE: glucmodel
#      MYSQL_USER: phpmyadmin
#      MYSQL_PASSWORD: Vz24Rik8*

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: cambiame
    ports:
      - "8081:80"

#  db1:
#    image: mysql:5.7
#    volumes:
#        - db_glucnet:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: glucnet
#      MYSQL_USER: root
#      MYSQL_PASSWORD: admin

  api1:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
    - .:/usr/src/build
    ports:
    - "5000:5000"
    depends_on:
      - db
volumes:
  db_model:
#  db_glucnet:

