# Generated by Django 3.1.2 on 2020-10-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.CharField(db_column='ID', max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
