# Generated by Django 3.1.1 on 2020-09-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro_investigacion',
            name='acronym',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='centro_medico',
            name='acronym',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='centro_investigacion',
            name='name',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='centro_medico',
            name='name',
            field=models.CharField(default=False, max_length=250),
        ),
    ]
