# Generated by Django 3.1.1 on 2020-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0002_auto_20200929_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_investigacion',
            name='acronym',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='centro_investigacion',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='centro_medico',
            name='acronym',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='centro_medico',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
