# Generated by Django 3.1.2 on 2020-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0002_auto_20201024_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, db_column='PASSWORD', max_length=255, null=True),
        ),
    ]
