# Generated by Django 3.1.2 on 2020-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0003_auto_20201024_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='sex',
            field=models.CharField(blank=True, db_column='SEX', max_length=255, null=True),
        ),
    ]
