# Generated by Django 3.1.1 on 2020-10-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0003_auto_20201002_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_investigacion',
            name='acronym',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='centro_medico',
            name='acronym',
            field=models.CharField(default='', max_length=10),
        ),
    ]
