# Generated by Django 3.1.1 on 2020-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0005_medico_medical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='investigation_ID',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
