# Generated by Django 3.0.5 on 2020-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPacientes', '0006_investigador_investigation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='patient_ID',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
