# Generated by Django 3.1.2 on 2020-10-23 05:50

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_investigacion', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('Investigator_type', models.CharField(choices=[('Research', 'Investigador de busqueda'), ('Analisis', 'Investigador de analisis'), ('Otro', 'otro tipo de investigador')], max_length=10)),
                ('investigation_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centro_investigacion.centro_investigacion')),
            ],
            options={
                'db_table': 'investigador',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
